### ISSUE TITLE
Document development workflows

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/iwg-workspace#10]
Document the workflows currently supported by our tools. the goal would be to understand and write down the current status before we discuss any changes.

**Comment by xgupta** [comment]
I think I can assign this task to myself. I will search the mailing list archive to know the status/previous discussion related to these tools & provide the links of them either in infrastructure_documentation.md or in a separate doc with the detailed summaries.

**Comment by ChristianKuehnel** [comment]
I guess some workflows are already documented on the website. And two of my colleagues have done tutorials ready that need to be added to the website , see #13
