### ISSUE TITLE
Create logo for the IWG

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/iwg-workspace#12]
I guess it would be nice to have a logo for our infrastructure working group. We could use that across our documents and tools.

**Comment by ZhiqianXia** [comment]
I know some websites can automatically generate logos, but I don't know if that's good enough. I'm sorry about my artistic taste.
https://www.logomaker.com/

**Comment by ChristianKuehnel** [comment]
I was playing with that tool and that got me thinking about some dragon-related logo. Maybe something like this:
https://dribbble.com/shots/6791305-Dragon-Logo-Design

(not sure about the licensing issues though...)

**Comment by xgupta** [comment]
BTW I also looked at a logo: https://pixy.org/616118/. A dragon is relaxing, It implies that we want to make compiler engineers work comfortable. 
Its license is [CC BY-NC-ND](https://en.wikipedia.org/wiki/Creative_Commons_license#Four_rights) 4.0 which means we need to give attribution for using it.

**Comment by ZhiqianXia** [comment]
I also have an idea to use LLVM's Logo directly, but we use a different color scheme, which represents us as a working group related to LLVM. Green has a earth-related, vibrant feel that fits well with our infrastructure group.

**Comment by xgupta** [comment]
That is also good idea. I think we may be do a quick voting for that. Zhiqian, would you share how it look like?

**Comment by ZhiqianXia** [comment]
@xgupta I known design a little, but I found a similar logo that basically consists of three elements: Dragon, color scheme,  name. https://www.cnx-software.com/wp-content/uploads/2011/10/LLVM-Logo-Derivative-1.png

**Comment by ChristianKuehnel** [comment]
closed after migration
