### ISSUE TITLE
[IRC] discord-irc bridge

### ISSUE THREAD

**Issue by xgupta** [ChristianKuehnel/iwg-workspace#16]
I open the issue to keep track the status of[ discord-irc ](https://github.com/reactiflux/discord-irc) bridge. I am happy to volunteer for this task with discord-admins if possible.

**Comment by ChristianKuehnel** [comment]
I pinged the discord moderators, lets see what they say: https://discord.com/channels/636084430946959380/642420509899882508/810823378364923904

**Comment by ChristianKuehnel** [comment]
Feedback from Eric:
They went for Discord so they could moderate the contents and make trolling/spamming harder. And also to be able to easily delete spam/trolling without the moderators constantly needing to scan for these.

So while a the bridge would be nice, it introduces new problems.

As much as I would like to smoothen the transition from IRC to Discord, I don't really have a good solution there...

**Comment by xgupta** [comment]
>So while a the bridge would be nice, it introduces new problems.

These topics have endless debates and opinions so I accept moderator's view -:)
