### ISSUE TITLE
[Code-Quality] Help in designing tblgen-format?

### ISSUE THREAD

**Issue by xgupta** [ChristianKuehnel/iwg-workspace#23]
A large portion of code is written using TableGen but we still don't have a formatter for it.
The aim of this open issue to coordinate with LLVM TableGen maintainer Paul and help him/community by listing challenges and designing tblgen-format.

**Comment by xgupta** [comment]
Do we add it to LLVM GSoC 2021 project list if it is fit in the scope of two month timeline? And Hopefully find a mentor and a student?

Though I don't have much knowledge on LLVM TableGen, I am more than happy to apply for the role of co-mentor.

Mentoring organization application deadline is 19 Feb. so we need add the project in the list if we want and have a mentor.

**Comment by ChristianKuehnel** [comment]
@Paul-C-Anagnostopoulos  what do you think?

Context on this issue: We're currently starting up the new [infrastructure working group](https://foundation.llvm.org/docs/infrastructure-wg/) and are collecting ideas for potential improvements, with this being one of these ideas.

**Comment by ChristianKuehnel** [comment]
@xgupta would we need to write such a formatter from scratch? 
Or are the some tools/frameworks that "only" need configuring (e.g. with a language syntax)?

**Comment by Paul-C-Anagnostopoulos** [comment]
I presume we are talking about a code formatter, correct? I've never been much of a fan of code formatters, but they are an integral part of the LLVM infrastructure, so it makes sense to create one for TableGen. I would be happy to help with this project.

**Comment by joker-eph** [comment]
clang-format claims to already supports TableGen somehow (haven't tried how good is it...).
There is a TableGen setting for the Language configuration: https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by xgupta** [comment]
Thanks, Paul for offering help. It is very appreciated. But really my knowledge is not enough to drive this project.  Also, we have some alternative available in the clang-format tool.
