### ISSUE TITLE
[Discord] Update the twitter-news bot to pull from the LLVM twitter feed as well

### ISSUE THREAD

**Issue by xgupta** [ChristianKuehnel/iwg-workspace#28]

**Comment by ChristianKuehnel** [comment]
Do you want to contact the Discord admins and discuss that directly with them?

**Comment by xgupta** [comment]
Personally, I first prefer this repository under LLVM org so tagging people for these matters look good.

**Comment by xgupta** [comment]
I will contact Discord admins.
