### ISSUE TITLE
Hold an initial meeting of the working group

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/iwg-workspace#3]
This might be difficult to schedule as the members are probably distributed across multiple time zones...

proposal for Agenda:
* Getting to know
* discuss first work items #5
* discuss how we want to work #4

**Comment by xgupta** [comment]
The majority of people will be joining from the USA I think. So what about 8 AM PST? It will clock at 12 AM in China from where few members will also join. But yes a quick poll will be a better choice to decide the time & video conferening tool.

**Comment by ChristianKuehnel** [comment]
Meeting scheduled for Thursday Feb 11th (8am PST, 5pm CET, 12am CST).

**Comment by ChristianKuehnel** [comment]
Meeting happened, minutes are in #17
