### ISSUE TITLE
Document how to find owners of BuildBots

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/iwg-workspace#37]
* add this to the BuildBot documentation
* point to worker page
* escalation 1: ask Galina
* escalation 2: ask IWG
* document CI machines not part of BuildBot

**Comment by ChristianKuehnel** [comment]
I would add a section to the [Developer Policy](https://llvm.org/docs/DeveloperPolicy.html#developer-policies)

Next step: draft the change and start a code review...
Rough outline of what I would say there:

### Working with the CI System
* main branch is checked by build bots 
  * add link, 
  * changes are checked AFTER they are committed to the main branch. It's OK to break the build if you fix it ASAP.
  * add link to bot config
  * explain bots are maintained by community members and master is maintained by Galina
* If your commit broke the build: 
  * fix it ASAP as this might block other contributors or downstream users.
  * If you need more time to fix it, please revert and commit again later. 
* If someone else broke the build and this blocks your work:
  * Comment on the code review in Phabricator (if available) or email the author, explain the problem and how this impacts you. Add a link to the broken build/error message so folks can understand the situation
  * Revert the commit if this blocks your work using `git revert <commit hash>`
* If a build/worker is permanently broken: 
  * 1st step: concat bot owner (with explanation how to find the owner)
  * 2nd step: escalate to Galina
  * 3rd step: escalate to IWG
* Other CI systems provided by the community (add links)
* for adding new configurations/workers see https://llvm.org/docs/HowToAddABuilder.html

**Comment by ChristianKuehnel** [comment]
Draft is ready for review: https://reviews.llvm.org/D97389

**Comment by ChristianKuehnel** [comment]
TODO for @ChristianKuehnel add a screenshot, it's still hard to understand where to find the owner instructions.

**Comment by ChristianKuehnel** [comment]
just uploaded a new patch with screenshot...

**Comment by ChristianKuehnel** [comment]
Waiting for an approval from Galina.

**Comment by ChristianKuehnel** [comment]
patch is upstream

**Comment by steveire** [comment]
This patch doesn't mention GreenDragon. I get emails about failures from that system too. Can you extend the docs to explain what it is?

**Comment by ChristianKuehnel** [comment]
Hi @steveire ,

I am not 100% sure what the convention on GreenDragon is, so I left that out. I had some discussions, but did not get a clear answer on that 😞
