### ISSUE TITLE
Agree on how we want to work and document it

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/iwg-workspace#4]
Questions to be answered:
* Where do we document our work?
  * Google Docs?
  * Markdown on Github?  
  * Should we migrate this GitHub project to LLVM? 
* What do we want to document?
  * meeting minutes should be public
  * List of members of the IWG
  * ...?
* Where to plan our work and document progress?
  * [Board on GitHub](https://github.com/ChristianKuehnel/iwg-workspace/projects/1)
* How do we communicate:
  * within the iwg?
    * for public topics: Discord + Discourse?
    * for private topics: iwg@llvm.org ?
    * video conferences: Google Meet, Zoom, ..? 
  * with the board?
    * Email?
    * Slack?
  * with the community?
    * Public documentation?
    * Discord, Discourse?
    * llvm-dev mailing list?

**Comment by ChristianKuehnel** [comment]
My proposal:

If we use **discord + discourse**, we can have our communication transparent for community and board members.

For complex texts (e.g. design documents, statement of work) I like **Google docs** because of the easy collaboration and commenting features. Once something is ready, I would export it to PDF our markdown and store it in git.

For planning our work, I would start with **GitHub issues** and see if they are powerful enough for our use cases. For that I would transfer this to llvm.

**Comment by ChristianKuehnel** [comment]
As we're distributed across time zones and English is not our native language, I guess it makes sense to communicate a lot in writing.

So Meike kindly set up a group on discourse for us: https://llvm.discourse.group/c/infrastructure/iwg/42
And also a channel on discourse: https://discord.com/channels/636084430946959380/802119671780081674

**Comment by ZhiqianXia** [comment]
The discourse channel link seems no longer valid.

**Comment by xgupta** [comment]
@ZhiqianXia You mean discord channel link? Please double-check as the link is working fine on my side :)

**Comment by ZhiqianXia** [comment]
@xgupta yes, I can open it from the web page, but there doesn't seem to be anyone there. Do you know how to get into this channel from the discord app? I've hardly ever used this tool.🙂

**Comment by xgupta** [comment]
No problem, My first discord server was also LLVM. 

1. After login as soon as you enter into the LLVM discord server (invite link: https://discord.gg/xS7Z362), the first channel you see is Code of Conduct. Now you need to click on the :white_check_mark:  to acknowledge CoC and gain access to other channels.

That is done, you will now see all channels and users of the LLVM discord server.

**Comment by ZhiqianXia** [comment]
@xgupta Thank you so much.😀

**Comment by ChristianKuehnel** [comment]
still some open question, but we're good to start...
