### ISSUE TITLE
Give overview on current situation and roadmap during virtual EuroLLVM    dev meeting (in April 2021)

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/iwg-workspace#7]
Goals:
* inform community about 
  * our work so far
  * our plans so far
* gather feedback

**Comment by xgupta** [comment]
We can also share a google doc that describes our meeting minutes. It makes it easy to create the final report.

**Comment by ChristianKuehnel** [comment]
meeting on 2021-03-30:
Too early for this --> closing the issue.
