### ISSUE TITLE
Document current project infrastructure

### ISSUE THREAD

**Issue by ChristianKuehnel** [ChristianKuehnel/iwg-workspace#9]
So that we have an overview of the current situation.

**Comment by ChristianKuehnel** [comment]
First draft in https://github.com/ChristianKuehnel/iwg-workspace/blob/main/infrastructure_documentation.md

**Comment by xgupta** [comment]
The TODOs should be fill by the respective administrators/maintainer. So we need to announce on llvm-dev that there is a doc that represents the status of the infrastructure tools? but I think people are more comfortable in opening pull requests when the page is available under the LLVM organization repository.

**Comment by ChristianKuehnel** [comment]
Next step, we discussed in our meeting:
* Try to collect all infrastructure components
* Agree which of these are in scope for this working group

Please add missing information by creating Pull Requests for [infrastructure_documentation.md](https://github.com/ChristianKuehnel/iwg-workspace/blob/main/infrastructure_documentation.md)

**Comment by ChristianKuehnel** [comment]
From the meeting minutes:
* Action item for Christian: rename file to "survey" 
  ([done](https://github.com/ChristianKuehnel/iwg-workspace/commit/d75fe71da959128c1bbbb42f026269d734bdb6ef))
* Goals:
  * have broad overview of all system to decide what we're working on.
  * avoid duplication of things already documented somewhere else
  * have overview page, not a documentation page, "curated set of links"
  * improve main/original LLVM documentation over time where needed
* Lots of tooling is community provided (volunteer efforts), should that be
  documented?
  * start with workflows, derive the important tools from these
  * Rather than writing up our own workflow documentation, provide links to
    commonly used workflows. We will then use these for our understanding of
    the critical infrastructure.
* action item (Christian): start list of know/documented workflows
  [#36](https://github.com/ChristianKuehnel/iwg-workspace/issues/36)
  * add Links to:
    * getting stared doc
    * developer policy
    * code review documentation
  * Encourage people to improve the original documentation where relevant
